# Creación de arrays con Numpy:

Funciones importantes para la creación de arrays.

## Numpy.array

Creación manual de un array.

In [105]:
import numpy as np
arreglo=np.array([[1,2],
                  [3,4]])

## Numpy.copy

In [109]:
import numpy as np
arreglo=np.array([[1,2],[3,4]]) 
copia=np.copy(arreglo)
# Equivalente a: 
#copia=np.array(arreglo,copy=True)

In [110]:
arreglo

array([[1, 2],
       [3, 4]])

In [111]:
copia

array([[1, 2],
       [3, 4]])

Si se realiza una modifiación:

In [112]:
arreglo[0][0]=4
arreglo

array([[4, 2],
       [3, 4]])

In [113]:
copia

array([[1, 2],
       [3, 4]])

## Numpy.arange

Array equiespaciado.

In [122]:
import numpy as np
arange=np.arange(3,7,1.5,dtype=int) #Inicio, final, paso
arange

array([3, 4, 5])

## Numpy.linspace

Array equiespaciado con cantidad dada.

In [129]:
import numpy as np
linspace=np.linspace(4,20,10,endpoint=False,dtype=int,retstep=True)
#retstep: muestra el paso que toma
linspace

(array([ 4,  5,  7,  8, 10, 12, 13, 15, 16, 18]), 1.6)

## Numpy.logspace

Array espaciado en escala logarítmica.

In [133]:
import numpy as np
log=np.logspace(1,10,10,base=4) #base^inicio,base^final,cantidad
log

array([4.000000e+00, 1.600000e+01, 6.400000e+01, 2.560000e+02,
       1.024000e+03, 4.096000e+03, 1.638400e+04, 6.553600e+04,
       2.621440e+05, 1.048576e+06])

## Numpy.empty

Crea un array con entradas no inicializadas.
Sirve para tener cierto arreglo que luego podemos modificar o ingresar valores.

In [11]:
import numpy as np
empty=np.empty([2,2]) # El argumento principal es la forma del arreglo
empty

array([[1.25975398e-311, 2.46151512e-312],
       [1.93101617e-312, 1.97345609e-312]])

### <span style="color:darkgray">Numpy.empty_like</span>

Todos las funciones "like" de Numpy tienen la misma función que la función original pero con un arreglo de referencia como entrada.

In [55]:
import numpy as np
a = ([1,2,3], [4,5,6])                         
np.empty_like(a)

array([[-1400739584,         593,           0],
       [          0,      131074, -2147483648]])

## Numpy.zeros, Numpy.ones y Numpy.full

Crea un array de ceros, unos o con determinado número con una forma determinada.

In [68]:
import numpy as np
cero=np.zeros((3,4))
uno=np.ones((2,5))
full=np.full((2,4),7.5)

In [61]:
cero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
uno

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
full

array([[7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5]])

### <span style="color:Darkgray">Numpy.zeros_like y Numpy.ones_like</span>

In [71]:
import numpy as np
arreglo=np.array([[1,2],[3,4]])
ceroslike=np.zeros_like(arreglo)
unoslike=np.ones_like(arreglo)
fulllike=np.full_like(arreglo,3)

In [64]:
ceroslike

array([[0, 0],
       [0, 0]])

In [65]:
unoslike

array([[1, 1],
       [1, 1]])

In [72]:
fulllike

array([[3, 3],
       [3, 3]])

## Numpy.identity

Crea una matriz identidad como un arreglo de Numpy.

In [67]:
import numpy as np
identidad=np.identity(4)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy.diag

Obtiene una diagonal de una matriz.

In [134]:
import numpy as np
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [138]:
diag=np.diag(x,k=-1) 
#k representa el número de la diagonal, por defecto k=0
diag

array([3, 7])